// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanSystem.Data;

#nullable disable

namespace UrbanSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241102152900_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrbanSystem.Data.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b2c7ff2-d6a2-487f-b5e3-1ac52410d926"),
                            CityName = "Blagoevgrad",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("4f9c66ae-e680-46e8-b4ca-7c9573189298"),
                            CityName = "Burgas",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("7bc44a26-bfbd-4b6b-a4c1-76d96ca639af"),
                            CityName = "Dobrich",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("b0225b6d-b916-46b5-a8d1-899705b56c8f"),
                            CityName = "Gabrovo",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("6a9675a2-132a-4494-b154-ae79d8b91d12"),
                            CityName = "Haskovo",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("97d10799-2116-4b2e-9e21-9f01076390e5"),
                            CityName = "Kardzhali",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("5f14d044-8e5f-441d-8a08-b22ce024d208"),
                            CityName = "Kyustendil",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("566dd22c-7393-42c6-ad61-18c79b0aa46e"),
                            CityName = "Lovech",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("b6403aed-f4ee-46e0-b18f-104a20cd479b"),
                            CityName = "Montana",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("c6fb5772-3761-4559-b83a-c1a15a2aff44"),
                            CityName = "Pazardzhik",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("429482ce-7fed-48c8-91b3-07ffcd0ec578"),
                            CityName = "Pernik",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("8b0ab1fa-1c83-4e36-8f95-28ee6851773b"),
                            CityName = "Pleven",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("4f9cf36a-71c8-4c77-875c-8945adadbeff"),
                            CityName = "Plovdiv",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("6bfba6b5-e821-4939-9aaf-8c9fd4a5918a"),
                            CityName = "Razgrad",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("32a4ed35-f032-4d89-88d4-88889761aa26"),
                            CityName = "Ruse",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("c79391d8-f3c5-4150-a399-aba2e0c29433"),
                            CityName = "Shumen",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("2c3e0582-53c0-4268-b3a7-42bcf2dfff66"),
                            CityName = "Silistra",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("3719cc70-9372-4fef-85c0-3e718b7021a3"),
                            CityName = "Sliven",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("33e5fa81-9144-45ee-9b57-a576a2bf7798"),
                            CityName = "Smolyan",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("1cd66606-fc52-48e2-9159-31af3efbc579"),
                            CityName = "Sofia",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("00dd078f-af4c-427e-8e47-f29d2237f161"),
                            CityName = "Stara Zagora",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("22edb1b3-0659-4eb0-b943-f502c0801889"),
                            CityName = "Targovishte",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("7a5d9877-243d-4e64-ba63-28deaa18b1b4"),
                            CityName = "Varna",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("8d0598da-dc4e-4e06-b2be-e7fcee8852e1"),
                            CityName = "Veliko Tarnovo",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("a882800e-eaae-4912-aed7-4442aeaf7cf1"),
                            CityName = "Vidin",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("deb6ead4-28df-441b-ae3a-21dd8c130a8a"),
                            CityName = "Vratsa",
                            StreetName = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("b7344ed3-9820-44ed-b034-2ebb3f8b0d5f"),
                            CityName = "Yambol",
                            StreetName = "Main Street"
                        });
                });

            modelBuilder.Entity("UrbanSystem.Data.Models.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Downvotes")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64a8408b-aa81-4f1e-aa57-e60eb3475c07"),
                            Category = "Transport",
                            Description = "Implement more frequent bus routes during peak hours to reduce congestion.",
                            Downvotes = 2,
                            Priority = "High",
                            Status = "Pending",
                            Title = "Improve Public Transport",
                            UploadedOn = new DateTime(2024, 11, 2, 15, 28, 59, 566, DateTimeKind.Utc).AddTicks(3116),
                            Upvotes = 10
                        },
                        new
                        {
                            Id = new Guid("acb4679b-6143-4edb-9d35-00576d2cd7c7"),
                            Category = "Environment",
                            Description = "Renovate the central park by adding new benches, lighting, and a playground area.",
                            Downvotes = 1,
                            Priority = "Medium",
                            Status = "Approved",
                            Title = "Park Renovation",
                            UploadedOn = new DateTime(2024, 11, 2, 15, 28, 59, 566, DateTimeKind.Utc).AddTicks(3124),
                            Upvotes = 25
                        },
                        new
                        {
                            Id = new Guid("480414ea-1514-48ca-adb9-30e3c7596d5c"),
                            Category = "Waste Management",
                            Description = "Introduce a recycling program and increase the frequency of waste collection.",
                            Downvotes = 0,
                            Priority = "High",
                            Status = "In Review",
                            Title = "Waste Management System",
                            UploadedOn = new DateTime(2024, 11, 2, 15, 28, 59, 566, DateTimeKind.Utc).AddTicks(3129),
                            Upvotes = 15
                        });
                });

            modelBuilder.Entity("UrbanSystem.Data.Models.SuggestionLocation", b =>
                {
                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SuggestionId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("SuggestionsLocations");
                });

            modelBuilder.Entity("UrbanSystem.Data.Models.SuggestionLocation", b =>
                {
                    b.HasOne("UrbanSystem.Data.Models.Location", "Location")
                        .WithMany("SuggestionsLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanSystem.Data.Models.Suggestion", "Suggestion")
                        .WithMany("SuggestionsLocations")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("UrbanSystem.Data.Models.Location", b =>
                {
                    b.Navigation("SuggestionsLocations");
                });

            modelBuilder.Entity("UrbanSystem.Data.Models.Suggestion", b =>
                {
                    b.Navigation("SuggestionsLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
