// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanSystem.Data;

#nullable disable

namespace UrbanSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241029221104_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrbanSystem.Data.Models.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Downvotes")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6dcc9c93-f8e3-4c85-83cd-c18c1ea58b7a"),
                            Category = "Transport",
                            CityName = "Sofia",
                            Description = "Implement more frequent bus routes during peak hours to reduce congestion.",
                            Downvotes = 2,
                            Priority = "High",
                            Status = "Pending",
                            StreetName = "Ne znam",
                            Title = "Improve Public Transport",
                            UploadedOn = new DateTime(2024, 10, 29, 22, 11, 3, 792, DateTimeKind.Utc).AddTicks(4108),
                            Upvotes = 10
                        },
                        new
                        {
                            Id = new Guid("c852ed10-70b7-4d9e-9fdd-6cb4ab407155"),
                            Category = "Environment",
                            CityName = "Sofia",
                            Description = "Renovate the central park by adding new benches, lighting, and a playground area.",
                            Downvotes = 1,
                            Priority = "Medium",
                            Status = "Approved",
                            StreetName = "Ne znam",
                            Title = "Park Renovation",
                            UploadedOn = new DateTime(2024, 10, 29, 22, 11, 3, 792, DateTimeKind.Utc).AddTicks(4113),
                            Upvotes = 25
                        },
                        new
                        {
                            Id = new Guid("6242e74d-bca9-4d79-946b-cea802088b7e"),
                            Category = "Waste Management",
                            CityName = "Blagoevgrad",
                            Description = "Introduce a recycling program and increase the frequency of waste collection.",
                            Downvotes = 0,
                            Priority = "High",
                            Status = "In Review",
                            StreetName = "Polk. Drangov 4",
                            Title = "Waste Management System",
                            UploadedOn = new DateTime(2024, 10, 29, 22, 11, 3, 792, DateTimeKind.Utc).AddTicks(4116),
                            Upvotes = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
